receivers:
  otlp:
    protocols:
      grpc:
      http:
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: 'fastpi-service-syncc'
  #         scrape_interval: 15s
  #         static_configs:
  #           - targets: ['fastpi-service-sync:8000']

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  # prometheus:
  #   endpoint: "0.0.0.0:8889"
  #   namespace: "otel-collector"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
